In [28]:
import numpy as np

def main():
    arr=np.array([[1,2],[3,4]])
    vec1=np.array([1,2,3])
    vec2=np.array([4,5,6])
    a=np.array([[1,2,-2],[2,1,-5],[1,-4,1]])
    b=np.array([[-15],[-21],[18]])
#     print(arr)
    
    eigval=np.linalg.eig(arr)[0]
    eigvect=np.linalg.eig(arr)[1]
    det=np.linalg.det(arr)
    
    print("Eigenvalues: \n",eigval)
    print("\nEigenvectors: \n",eigvect)
    print("\nDeterminant: {0:2.2f}".format(det))
    print("\nCross product: \n",np.cross(vec1,vec2))
    print("\nSolution: \n",np.linalg.solve(a,b))
    
    
if __name__=='__main__':
    main()

Eigenvalues: 
 [-0.37228132  5.37228132]

Eigenvectors: 
 [[-0.82456484 -0.41597356]
 [ 0.56576746 -0.90937671]]

Determinant: -2.00

Cross product: 
 [-3  6 -3]

Solution: 
 [[-1.]
 [-4.]
 [ 3.]]
